[tools]
node = "24"
"npm:@infisical/cli" = "latest"
typos = "latest"
"ubi:trufflesecurity/trufflehog" = "latest"

[env]
_.path = ['./node_modules/.bin']
_.file = '.env.deployer'

[tasks.start-dev]
description = "start docker-compose for dev environment and bot"
run = """
infisical run --env=dev -- docker compose -f docker-compose.dev.yml up -d && \
sleep 20 && \
infisical run --env=dev -- bun --filter="@packages/database" run db:push
"""

[tasks.dev]
description = "start dev environment and bot"
run = "bun run bot:dev"

[tasks.stop-dev]
description = "stop docker-compose for dev environment"
run = """
docker compose -f docker-compose.dev.yml down --remove-orphans --volumes
"""

[tasks.start-prod]
description = "start docker-compose for production environment"
run = """
infisical run --env=prod -- docker compose -f docker-compose.yml up -d
"""

[tasks.stop-prod]
description = "stop production docker-compose"
run = """
docker compose -f docker-compose.yml down
"""
