/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/generate': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Deep research
     * @description Generate a response using the Silver deep research agent API.
     */
    post: operations['postGenerate']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/text-generation': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Generate text
     * @description Generate text
     */
    post: operations['postText-generation']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Health check
     * @description Check if the server is healthy
     */
    get: operations['getHealth']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/models': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get available models
     * @description Get list of available models for each mode
     */
    get: operations['getModels']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: never
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  postGenerate: {
    parameters: {
      query?: never
      header: {
        authorization: string
      }
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': {
          app: string
          prompt: string
          /** @enum {string} */
          mode: 'auto' | 'pro' | 'reasoning' | 'deep research'
          model?: string
          sources: ('web' | 'scholar' | 'social')[]
          userId?: string
          guildId?: string
          username?: string
          guildName?: string
        }
        'application/x-www-form-urlencoded': {
          app: string
          prompt: string
          /** @enum {string} */
          mode: 'auto' | 'pro' | 'reasoning' | 'deep research'
          model?: string
          sources: ('web' | 'scholar' | 'social')[]
          userId?: string
          guildId?: string
          username?: string
          guildName?: string
        }
        'multipart/form-data': {
          app: string
          prompt: string
          /** @enum {string} */
          mode: 'auto' | 'pro' | 'reasoning' | 'deep research'
          model?: string
          sources: ('web' | 'scholar' | 'social')[]
          userId?: string
          guildId?: string
          username?: string
          guildName?: string
        }
      }
    }
    responses: {
      /** @description Response for status 200 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            text: string
            backend_uuid?: string
            /** @default [] */
            web_results: unknown[]
            dict?: unknown
          }
        }
      }
    }
  }
  'postText-generation': {
    parameters: {
      query?: never
      header: {
        authorization: string
      }
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': {
          app: string
          prompt: string | {
            content: string
            role: 'system' | 'user' | 'assistant'
            name?: string
          }[]
          system_prompt: string
          userId?: string
          guildId?: string
          username?: string
          guildName?: string
        }
        'application/x-www-form-urlencoded': {
          app: string
          prompt: string | {
            content: string
            role: 'system' | 'user' | 'assistant'
            name?: string
          }[]
          system_prompt: string
          userId?: string
          guildId?: string
          username?: string
          guildName?: string
        }
        'multipart/form-data': {
          app: string
          prompt: string | {
            content: string
            role: 'system' | 'user' | 'assistant'
            name?: string
          }[]
          system_prompt: string
          userId?: string
          guildId?: string
          username?: string
          guildName?: string
        }
      }
    }
    responses: {
      /** @description Response for status 200 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            ok: boolean
            output?: string
            error?: string
          }
        }
      }
    }
  }
  getHealth: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Response for status 200 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            status: string
          }
        }
      }
    }
  }
  getModels: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Response for status 200 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            models: {
              auto: ((string | null) | null)[]
              pro: ((string | null) | null)[]
              reasoning: ((string | null) | null)[]
              'deep research': ((string | null) | null)[]
            }
          }
        }
      }
    }
  }
}
